server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - argocd.local
    tls:
      - hosts:
          - argocd.local
  service:
    type: ClusterIP
    port: 443

