apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-project
  namespace: argocd   
spec:
  project: project-1
  source:
    helm:
      releaseName: "application-from-helm"
      valueFiles:
              - custom-values.yaml
    repoURL: https://github.com/Rohit4530/argocd-project.git
    targetRevision: main
    path: argocd-applications/v04-project/wordpress-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
