apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: project-1
    namespace: argocd
spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    sourceRepos:
    - 'https://github.com/Rohit4530/argocd-project.git'
